### ISSUE TITLE
modulo gestion cuentas contables

### ISSUE THREAD

**Issue by salcedogeiner** [udistrital/financiera_cliente#17]
Se ampliará con módulo que gestione cuentas contables para los procesos del sistema

**Comment by faparraf** [comment]
Cual es el estado de este issue, ya se encuentra solucionado?

**Comment by salcedogeiner** [comment]
el modulo para la gestion de cuentas contables cuenta con la posibilidad de crar nuevas cuentas en el plan maestro y de igual manera visualizarlas, falta la modificación de estas que por reglas del negocio se tratara en otro modulo.
