### ISSUE TITLE
Redirección de las opciones de egresos a endpoins de presupuesto

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/financiera_cliente#529]

**Comment by Miavega** [comment]
revision RP aprobacion-anulacion

[commit](https://github.com/udistrital/financiera_cliente/commit/ffcb79b13cb1c4beb884b68f281ef38757b20138)

**Comment by JuanPiedrahita** [comment]
Se revisa y pasan los endpoints para solicitudes de CRP (https://github.com/udistrital/financiera_cliente/commit/b11140503dac398da806be0e7bcce7af890aaee1).

**Comment by JuanPiedrahita** [comment]
Se revisa y pasan los endpoints para consulta de CRP ([commit](https://github.com/udistrital/financiera_cliente/commit/c374b394d9311aa1274bccf6b7f4181b10d70253)).

**Comment by miguelramirez93** [comment]
Revisado. No se tienen observaciones

**Comment by jjvargass** [comment]
observaciones:

1. Logica quemada 
https://github.com/udistrital/presupuesto_crud/commit/d056deb654cd2637d996f8f11fee27e1ccd2203c#diff-f35a5927f0a35003f3a58a6a9bad3a1eR205

2. la serialización que se panteo para las apis no se esta realizando
https://github.com/udistrital/presupuesto_crud/commit/d056deb654cd2637d996f8f11fee27e1ccd2203c#diff-f35a5927f0a35003f3a58a6a9bad3a1eR164
