### ISSUE TITLE
Revisar modelo de negocio y avancede desarrollo de ingresos e ingresos sin situación de fotos para sub sistema de presupuesto de kronos - cliente

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/financiera_cliente#530]
Revisar modelo de negocio de kronos y avance de los desarrollos en los ambientesde pruebas

**Comment by JuanPiedrahita** [comment]
Se realiza revisión del modelo de negocio de ingresos y modelo de base de datos teniendo en cuenta la [documentación ](https://drive.google.com/folderview?id=0B8NdjGOtWwjCMk1LMHpYQkRBeUk)  entregada por Maria C. Se genera [documento de resumen](https://docs.google.com/document/d/1zFPgNkkfhipOJV9RBEyopsuZtfB9_IutPA11nnHqvTk/edit?usp=drivesdk).

**Comment by JuanPiedrahita** [comment]
Se realiza revisión de endpoints que se consumen desde el cliente para paso de api a microservicios, se genera [documento de análisis](https://docs.google.com/document/d/1YL2omZg_6JOKJrIq4I78IEFWcjPEZLjpRJAZW1g3FaA/edit?usp=drivesdk).

**Comment by miguelramirez93** [comment]
Los documentos referenciados son los mismos de este [issue](https://github.com/udistrital/api_financiera/issues/245) pero la tarea se refiere al cliente , los documentos contienen datos de end points pero no de las funcionalidades a nivel cliente . Por favor dar las razones por las cuales no se generarón documentos de analisis de los módulos del cliente

**Comment by JuanPiedrahita** [comment]
Miguel se dejan los mismos documentos porque desde el analisis que se realizo se discrimaron los endpoints según eran consumidos por los diferentes modulos del cliente, asi que, en el [documento  de análisis](https://docs.google.com/document/d/1YL2omZg_6JOKJrIq4I78IEFWcjPEZLjpRJAZW1g3FaA/edit) se puede ver discriminados los endpoints que se consumen teniendo en cuenta cada submenu del arbol del cliente.

En cuanto a la documentación entregada por Maria C, se tienen en cuenta que en dichos documentos se encuentra información tanto del cliente como del modelo que se crea para los ingresos.

**Comment by Miavega** [comment]
Se apoya la revisión de endpoinst consumidos desde el cliente para paso de API a microservicios, identificándolos en el [documento](https://docs.google.com/document/d/1YL2omZg_6JOKJrIq4I78IEFWcjPEZLjpRJAZW1g3FaA/edit)

**Comment by miguelramirez93** [comment]
Revisado y aprobado el documento .
