### ISSUE TITLE
Pasar egresos - CDP a microservicio - Cliente

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/financiera_cliente#532]
Redirección endpoints de egresos a mid y crud.

**Comment by JuanPiedrahita** [comment]
Redirección de endpoints a nuevos servicios de presupuesto para anulación de CDP's https://github.com/udistrital/financiera_cliente/commit/316cc9a591fbf8e0a10ff5094a83153af30cb272.

**Comment by JuanPiedrahita** [comment]
Redirección de endpoints a nuevos servicios de presupuesto para consulta de CDP's https://github.com/udistrital/financiera_cliente/commit/d8ea23e65fbdffade83d1404b9a38f7347dbb56c.

**Comment by JuanPiedrahita** [comment]
Redirección de endpoints a nuevos servicios de presupuesto para solicitud de CDP's https://github.com/udistrital/financiera_cliente/commit/00ed348a2e71c625f1cc759cf10cb9cec358f636.

**Comment by miguelramirez93** [comment]
Se revisa el redireccionamiento , todo acorde a lo esperado.
