### ISSUE TITLE
Macroproceso del Subsistema de Tesorería

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#534]

**Comment by mcrubianot** [comment]
Se realiza el levantamiento del Macroproceso del Subsistema de Tesorería

Se encuentra en el siguiente link. 
https://drive.google.com/open?id=1z8io_dwuO_BPO7dc_KgSotwHrka-McJZ

**Comment by mcrubianot** [comment]
Se ajusta de acuerdo a lo solicitado en acta No.2 de Kronos.

**Comment by Soulfilip-UD** [comment]
El procedimiento fue documentado, y lo referente al seguimiento fue finalizado. Se cierra el Issue
