### ISSUE TITLE
Macroproceso del Subsistema de Central de Cuentas

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#535]

**Comment by mcrubianot** [comment]
Se levanta el respectivo macroproceso, se encuentra en el siguiente link.

https://www.draw.io/?state=%7B%22folderId%22:%2217yJxosIs5NbeUlxmeITTfSArwnCdhY_V%22,%22action%22:%22create%22,%22userId%22:%22115577396714392713055%22%7D#G1nSiCQDubfyf746-SENkcoiuaj3vE7_f8

**Comment by mcrubianot** [comment]
Se puede cerrar queda pendiente la validación de este macro con el usuario, lo cual se levantará en un nuevo issue.

**Comment by Soulfilip-UD** [comment]
Se da por finalizado el Issue
