### ISSUE TITLE
Macroproceso del Subsistema de Contabilidad

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#536]

**Comment by mcrubianot** [comment]
Se asigna esta tarea al ingeniero Fausto Puerto, quien será el encargado de levantar los requerimientos de este Subsistema.

**Comment by mcrubianot** [comment]
Se puede cerrar, de acuerdo a lo establecido esta es una tarea que le ha sido asignada al ingeniero Fausto.  Considero que él tendría que abrir uno nuevo.

**Comment by Soulfilip-UD** [comment]
Se da por finalizado el Issue
