### ISSUE TITLE
Revisión y análisis de nuevas características de Sistema KRONOS

### ISSUE THREAD

**Issue by mcguegi** [udistrital/financiera_cliente#537]
Se realiza un análisis de los siguientes repositorios

- financiera_cliente
- financiera_mongo_crud
- presupuesto_mid
- presupesto_crud

Con el fin de observar y tener en cuenta los últimos cambios de algunos módulos para aplicarlo al módulo de Fuentes de Financiamiento. Esta información está siendo consignada en un documento.

**Comment by mcguegi** [comment]
Se adjunta el enlace al documento elaborado resaltando las nuevas características del subsistema de presupuesto
[Documento Disponible Aquí](https://docs.google.com/document/d/1q4gadj_Th09LAfYvEfC_854rdiHUgC9omPU8Depn0ag/edit?usp=sharing)

**Comment by mcguegi** [comment]
Se realiza análisis del Cliente y sus correspondientes servicios .

**Comment by CarlosGutierrezArdila** [comment]
Se hace análisis de cada uno de los endpoint del mid encontrando situaciones de código repetido y llamadas estáticas a servicios, así mismo se identifican los elementos del modelo de datos que tienen que ver con fuentes de financiamiento.

**Comment by miguelramirez93** [comment]
Se revisa el documento, el analisis cumple con la meta de la tarea .
