### ISSUE TITLE
Macroproceso del Subsistema de Presupuesto

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#538]

**Comment by mcrubianot** [comment]
Se levanta el respectivo macroproceso y se presenta a la Sección de Presupuesto

https://drive.google.com/open?id=1dsmYkB8O8gSn1mHVwoMpJCowxax3sINa

**Comment by mcrubianot** [comment]
Se presenta al usuario. Se levanta el acta No.1.

https://docs.google.com/document/d/104-a-y9FpNpHfsDREbqC29QwVKNCHnkEguCNycp7jYU/edit

**Comment by mcrubianot** [comment]
Se hacen los ajustes solicitados de acuerdo al acta anterior. Se registra en el siguiente link.

https://www.draw.io/?state=%7B%22ids%22:%5B%221-0O1vMIhGNrdi-8v8BsyQKdlTxHUGOT9%22%5D,%22action%22:%22open%22,%22userId%22:%22115577396714392713055%22%7D#G1-0O1vMIhGNrdi-8v8BsyQKdlTxHUGOT9

**Comment by mcrubianot** [comment]
Acta sin aprobar por parte del usuario

**Comment by mcrubianot** [comment]
Se recibe el siguiente correo

De: Janeth Molina Velandia <jmolinav@udistrital.edu.co>
Date: vie., 24 may. 2019 a las 11:52
Subject: Re: Acta No.01 - Kronos
To: Oficina Asesora de Sistemas Universidad Distrital <computo@udistrital.edu.co>
Cc: Presupuesto Universidad Distrital <presup@udistrital.edu.co>


Buenos días, el acta esta de acuerdo a lo hablado y establecido en la reunión.

Cordialmente

Janeth Molina V.
Sección de Presupuesto
Ext 1758

**Comment by Soulfilip-UD** [comment]
El procedimiento fue documentado, y lo referente al seguimiento fue finalizado. Se cierra el Issue
