### ISSUE TITLE
Levantamiento de Requerimientos del procedimiento de Avances

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#540]

**Comment by mcrubianot** [comment]
En desarrollo de esta tarea se levanta el acta No. 3 Gestión de Avances - Subsistema de Tesorería

https://docs.google.com/document/d/1cV6FCfl16wAE_kNxuqdosrE3uvMgaC94I6Vb0rixXZc/edit

**Comment by mcrubianot** [comment]
Se recibe el siguiente correo

Legalizacion Avances <legalizacionavances@udistrital.edu.co>
--
para: | "Maria Claudia Rubiano ..." <mcrubianot@udistrital.edu.co>
fecha: | 28 may. 2019 8:18
asunto: | RE: Acta No.3 - Gestión Avances - Kronos - Invitación para editar

**Comment by mcrubianot** [comment]
Se envió el siguiente correo 

de: | Maria Claudia Rubiano Torres <mcrubianot@udistrital.edu.co>
-- | --
para: | Legalizacion Avances <legalizacionavances@udistrital.edu.co>
fecha: | 31 may. 2019 10:55
asunto: | Re: Acta No.3 - Gestión Avances - Kronos - Invitación para editar

Hola pia buenos días.

El diagrama al que Usted se refiere está publicado en el Sigud  GRF-PR-012, Avances. Al estar allí, la modificación que se debe hacer, debe solicitarla la Sección de Tesorería directamente.

Los únicos que puedo modificar son los que estamos analizando las dos, antes de que se publiquen en el Sigud y de acuerdo a nuestra reunión, se están haciendo los ajustes del caso. Una vez estén ajustados nos reuniremos para su validación.

Gracias por la atención.

**Comment by mcrubianot** [comment]
No se ha recibido observación alguna por parte del usuario. De nuestra parte se presentó el procedimiento y fue avalado.

Se puede dar por cerrado el issue.

**Comment by Soulfilip-UD** [comment]
Se da por finalizado el Issue
