### ISSUE TITLE
Acompañamiento en la construcción del documento "Análisis general de los procesos"

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#543]

**Comment by mcrubianot** [comment]
Teniendo en cuenta el requerimiento del Gerente del Proyecto, ser realiza el acompañamiento en la construcción del documento "Análisis general de los procesos", el cual contiene toda la información relacionada con la parte documental del proyecto de Sistema de Gestión Financiera - Kronos.

Actividades realizadas durante los días 6, 7 y 10 de junio de 2019

https://docs.google.com/spreadsheets/d/1FvqXr8MweOZIaztPh9OEtEsXU4nI3j8gQeriP2-Ac1Y/edit#gid=0

**Comment by mcrubianot** [comment]
Se relacionan en este archivo los procedimientos que están relacionados en el Sigud, los cuales se modificarán, teniendo en cuenta que ya se integraría la interoperabilidad con los otros sistemas, pero se dejan relacionados para mayor comprensión del modelo de negocio.

**Comment by Soulfilip-UD** [comment]
El procedimiento fue documentado, y lo referente al seguimiento fue finalizado. Se cierra el Issue
