### ISSUE TITLE
Levantamiento modelo actual de necesidades

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#547]

**Comment by mcrubianot** [comment]
Se recopila la información que se tiene con respecto a necesidades de acuerdo a las actividades realizadas durante las vigencias anteriores::

https://drive.google.com/open?id=1BWJso9LIYmQD052xvBZ0QFO0t2eAUQjB

https://drive.google.com/open?id=1XKH5oDAO449-xQY5o1IE5_jpAZRe9iNf

https://drive.google.com/open?id=1QBbiB8mo205dLAxuoFoeC5bxoFM_ea8b

**Comment by mcrubianot** [comment]
Se inicia el levantamiento del modelo actual

https://docs.google.com/document/d/1e2DUwxetuoXfyK_aCSECiU12PwQS-v2DhPeE5Wq2Xec/edit

**Comment by mcrubianot** [comment]
Se da por terminado el levantamiento, quedo a la espera de las aclaraciones que me sean solicitadas al respecto.

**Comment by DianaPatriciaRamirez** [comment]
En acta 15 del 22 de agosto de 2019 se realizó revisión y aprobación de los mockups para solicitud de Necesidad:

https://drive.google.com/drive/folders/16DrfSRB2AMEBitblaXCp0Sm83J6Xwavq
https://docs.google.com/document/d/1Qk9z7IWx11rtHLpyzE-m5g-aV1tRz2d1UKXmcb5dguo/edit

El 9 de diciembre de 2019 en acta 23, se presenta a los usuarios el módulo de necesidades:

https://pruebasnecesidades.portaloas.udistrital.edu.co/#/
https://docs.google.com/document/d/1sWueC7aoNUjm8b3F-_9MP3t29ksC6tD25WOHGK_ThpY/edit
https://drive.google.com/open?id=0B-BNiTbtzIfeTm54VFBBVXJES29nTkEtbng4czNQNzg3N0xv
https://docs.google.com/spreadsheets/d/1Vr5hLC0-gflsr-5_VQbsM7ls1FglyjSBgIrZCEolrQM/edit#gid=1652234617
https://drive.google.com/drive/folders/14r6D9108rK2NJ0AS0YEUwEPcQ5mpdbiO

El 11 de diciembre, la Oficina Asesora de Sistemas envió correo electrónico a los usuarios finales solicitando la aprobación de las historias de usuario y la funcionalidad del módulo de gestión de necesidades. Así mismo, también se solicitó realizar las pruebas funcionales y de usabilidad.
