### ISSUE TITLE
Elaboración Flujogramas Kronos

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#551]

**Comment by mcrubianot** [comment]
Se elabora el respectivo Flujograma de solicitud y aprobación de los certificados de registro presupuestal

https://www.draw.io/?state=%7B%22ids%22:%5B%221yXu04niuyCF2BqTeAdTqTI3Mdktk-GCr%22%5D,%22action%22:%22open%22,%22userId%22:%22115577396714392713055%22%7D#G1yXu04niuyCF2BqTeAdTqTI3Mdktk-GCr

**Comment by mcrubianot** [comment]
Se elabora el Fujograma de Preasignación Apropiación Inicial

https://www.draw.io/?state=%7B%22folderId%22:%221EDQlGka2L1xpriFUyeXuhgGYuetVyLN3%22,%22action%22:%22create%22,%22userId%22:%22115577396714392713055%22%7D#G1LbLmONlMflI8lfWY8guPx87edBUvrQYV

**Comment by mcrubianot** [comment]
Se elabora el Fujograma de Creación concepto tesorales

https://www.draw.io/?state=%7B%22folderId%22:%220B8NdjGOtWwjCZUVHdFdkVkQ0QU0%22,%22action%22:%22create%22,%22userId%22:%22115577396714392713055%22%7D#G1QCNsm1lu6a-Ypvoz31a_szvuihQ35d2o

**Comment by mcrubianot** [comment]
Se revidan los flijogramas de la gestión de bancos y se determina que estén los documentos de análisis asi:

Creación de bancos
 https://www.draw.io/?state=%7B%22ids%22:%5B%2216aiwxRaL680d6LQD8hqb7YvbwNkPr2oH%22%5D,%22action%22:%22open%22,%22userId%22:%22115577396714392713055%22%7D#G16aiwxRaL680d6LQD8hqb7YvbwNkPr2oH

Sucrusales 
https://docs.google.com/document/d/1bj2aC-7OkQn0Vm_38ZUvlaTrY-4aGEV6PjXnZOFmuFk/edit

Saldos iniciales
https://docs.google.com/document/d/1B0dL1Be7syox3xp5M-raQYMn8MEwDc_xso8isT-dn_0/edit#

Consulta de movimiento
https://docs.google.com/document/d/14BmpZJtRelUx9kHvnZp-Utxx7ebzB08LNOXcvCSeYd4/edit#

**Comment by mcrubianot** [comment]
Con respecto a los flujogramas que se están elaborando, es preciso indicar que a la fecha no se han podido validar con los usuarios pues no se han podido hacer las reuniones correspondientes. No existen actas de validación por parte del usuario final.

**Comment by Soulfilip-UD** [comment]
Tarea exitosa, y a la fecha se han podido validar varios flujogramas, el seguimiento se dara en otro Issue 

Proceeding to close Issue 👾
