### ISSUE TITLE
Reunión de Presentación de Kronos al IDEXUD

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#552]

**Comment by mcrubianot** [comment]
Se realizó presentación el día 08/07/2019 en las instalaciones del Idexud, con el fin de poner en conocimiento el proyecto. Se inición a las 2:30 p.m. hasta las 4:00 p.m.

**Comment by mcrubianot** [comment]
https://drive.google.com/open?id=1WnoGpp3-c_Ac8g6e1ShZJR23JsOtFNnQf3HyOL2inyQ

**Comment by Soulfilip-UD** [comment]
Tarea Realizada

Proceeding to close Issue 👾
