### ISSUE TITLE
Elaborar V2 de Historias de Usuario de Creación de Productos, Asignar Producto a un Rubro

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#555]

**Comment by mcrubianot** [comment]
Se crea la historia de Usuario de Crear producto y consultar producto V2

https://docs.google.com/spreadsheets/d/1nWi12BAHfiVE7UoT4Mz9yY_RbJNp7jgWYMl-fvrf-18/edit#gid=852078008

**Comment by mcrubianot** [comment]
Asignar un producto a un rubro

https://docs.google.com/spreadsheets/d/1YskU_S0EJAe_hOhyw5B8mOlbAJDxN0gM8X-w8ffWDgs/edit#gid=852078008

**Comment by DianaPatriciaRamirez** [comment]
Ya existe una Versión 3 de las HU:

HU - Productos V3 https://docs.google.com/spreadsheets/d/1dT4e0Ar-jDmqI73gOMALkVvyIueQ9LGF7X1hDlKj6Dk/edit#gid=852078008

HU - 18 Asignación de Productos a un rubro V3 https://docs.google.com/spreadsheets/d/1rQXDV6SE4MMn0rylUfC5tZN74_UQ3UavWBlsSZUtMBs/edit#gid=852078008
