### ISSUE TITLE
Elaborar V2 de Historias de Usuario de Anulaciones presupuetales

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#557]

**Comment by mcrubianot** [comment]
Se elaboran las V2 de las historias de usuario de anulaciones totales  y parciales de CDP

https://docs.google.com/spreadsheets/d/1PMjr74pHUu4vhGZIevQ7XI3bdz8579Emh7tP4xzcbKg/edit#gid=852078008

**Comment by mcrubianot** [comment]
Se elaboran las V2 de las historias de usuario de anulaciones totales y parciales de CRP

https://docs.google.com/spreadsheets/d/174SKw8YPJ_gG0bGLmOBa83yEIHHg4GyAg6acc5Tjqno/edit#gid=852078008

**Comment by DianaPatriciaRamirez** [comment]
Ya se encuentra la V3 de las HU:

HU - 40 A 42 - Anulacion Total y Parcial de Reservas V3 https://docs.google.com/spreadsheets/d/1KtBll3BwQrJiiUd24AZruAUpoHvCa8uko1WQtM4utsE/edit#gid=852078008

@mcrubianot Por favor dejar la trazabilidad completa dentro de cada issue. Muchas gracias.
