### ISSUE TITLE
Reunión entendimiento del modelo de negocio de contabilidad

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#560]

**Comment by mcrubianot** [comment]
Se revisará en dicha sesión de trabajo los modelos de negocio del plan de cuentas contable (general y alterno), descuentos e impuestos y la gestión de comprobantes (consulta de comprobantes y creación de tipo de comprobantes) que es lo que se lleva analizado hasta el momento en este Subsistema

**Comment by mcrubianot** [comment]
Se analiza en conjunto con el ingeniero Fausto Puerto, los temas antes mencionados y se comparte la información que en su momento se había trabajado para análisis.

https://drive.google.com/open?id=0B8NdjGOtWwjCZnJQSUlwMlNCXzA

**Comment by mcrubianot** [comment]
Se compartieron, documentos de analisis de plan maestro, plan alterno, descuentos, comprobantes. Dentro de ellos la V1 de las historias de usuario

https://drive.google.com/open?id=11SApfT1d8YP7BmuWa-oNJoyRiNIL0gRO

**Comment by mcrubianot** [comment]
de: | Maria Claudia Rubiano ... (vía Google Drive) <drive-shares-noreply@google.com>
-- | --
responder a: | "Maria Claudia Rubiano ..." <mcrubianot@udistrital.edu.co>
para: | mcrubianot@udistrital.edu.co
Cc: | fapuertoq@udistrital.edu.co
fecha: | 22 jul. 2019 15:02
asunto: | SUBSISTEMA DE CONTABILIDAD - Invitación para colaborar

mcrubianot@udistrital.edu.co te ha invitado a colaborar en la siguiente carpeta compartida:

SUBSISTEMA DE CONTABILIDAD
Unknown profile photo	Ingeniero para tener en cuenta en los procesos de análisis y desarrollo del Subsistema de contabilidad.

Quedo atenta a cualquier aclaración que requiera

**Comment by FaustoPuerto** [comment]
Se revisó la información, quedando a la espera de la definición por parte del área técnica de la viabilidad de mantener y afinar el desarrollo realizado a la fecha para su presentación ante el usuario delegado.

**Comment by mcrubianot** [comment]
Se dió el día 13/08/2019 otra explicación al señor Fausto Puerto respecto a los procedimientos
- Plan de Cuentas
- Comprobantes
