### ISSUE TITLE
Reunión procesos Sicapital y Kronos - oficio IE 23198 (Idexud)

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#571]

**Comment by mcrubianot** [comment]
Se estableció en esta reunión que se enviaran las historias de usuario del Subisistema de Presupuesto para revisión y posterior mesa de trabajo. 

Se solicitó por parte del Idexud enviar formato para poder dar permisos para elaboración de conceptos en sicapital.

Se debe hacer un análisis de la creación de otra Unidad Ejecutora en el Sicapital y el ajuste en los dígitos del último nivel para incluir otros números.

**Comment by mcrubianot** [comment]
Se envia correo con el formato y las historias de usuario

**Comment by mcrubianot** [comment]
de: | Oficina Asesora de Sistemas Universidad Distrital<computo@udistrital.edu.co>
-- | --
para: | "Instituto de Extensión y de Educación no formal (IDEXUD) Universidad Distrital" <idexud@udistrital.edu.co>
Cco: | mcrubianot@udistrital.edu.co
fecha: | 15 ago. 2019 12:32
asunto: | Remisión Historias de Usuario y formato de solicitud de usuarioBuenos días, de conformidad con los compromisos adquiridos en la mesa de trabajo el día de ayer 14/08/2019, comedidamente nos permitimos remitir:

1. Formato de solicitud de usuario de Sicapital para acceso al Módulo de Tesorería para poder crear los diferentes conceptos para la vigencia 2019 de la Unidad Ejecutora 02.

2. Con respecto al nuevo Sistema de Gestión Financiera Kronos, nos permitimos remitir las historias de usuario de los siguientes procedimientos para su revisión y observaciones:

- Rubros Presupuestales
- Preasignación apropiación inicial
- Apropiación inicial

Quedamos atentos a sus comentarios.


Cordialmente, 
 
OFICINA ASESORA DE SISTEMAS

**Comment by DianaPatriciaRamirez** [comment]
@mcrubianot Por favor adjuntar evidencia de aprobación de estas HU por parte del IDEXUD.
