### ISSUE TITLE
Asistencia reunión Subsistema de Contabilidad  - Kronos

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#583]

**Comment by mcrubianot** [comment]
Se planteo reunión con la Sección de Contabilidad el día 28 de agosto de 2019. 

El acta la levantará el ingeniero Fausto Puerto

**Comment by FaustoPuerto** [comment]
La reunión se realizó entre las 9:00 a.m.y las 10:40 a.m. en la Sala de Juntas de la División de Recursos Financieros.

El acta de la reunión se encuentra disponible en el siguiente enlace:
https://docs.google.com/document/d/1CfmhAi6qRHu7OiSXWjzFnn_IxnKrBtUjadPMQVT7MgM/edit?ts=5d6817e9&pli=1
