### ISSUE TITLE
Reunión con Sección de Contabilidad, levantamiento de requerimientos - Acta No,17

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#586]

**Comment by mcrubianot** [comment]
Se envió el siguiente correo


de: | Oficina Asesora de Sistemas Universidad Distrital <computo@udistrital.edu.co>
-- | --
para: | Contab <contab@udistrital.edu.co>,Ernesto Suastegui Molina <esuasteguim@udistrital.edu.co>,Maria Helena Gonzalez Franco <mhelenagonzalez@hotmail.com>
Cco: | mcrubianot@udistrital.edu.co

Cordial saludo:

De manera atenta  y con el fin de continuar con los procesos que se vienen desarrollando me permito invitarlo  a la reunión del Subsistema de Contabilidad - Levantamiento de Requerimientos - el martes 17  de septiembre a las 8:00 a.m. que se realizará en la Sala de Juntas de la División de Recursos Financieros.
Agradezco su asistencia,

Cordialmente,


OFICINA ASESORA DE SISTEMAS
Universidad Distrital Francisco José de Caldas

**Comment by mcrubianot** [comment]
Se asiste a dicha sesión de trabajo y se levanta la respectiva acta.

Acta No.17
https://drive.google.com/open?id=1fyUtkNZnn-bBYBdcj8oivyO_dmcdgzMNlAznctr_G04

**Comment by mcrubianot** [comment]
Se comparte dicho documento para observaciones


de: | Maria Claudia Rubiano ... (vía Documentos de Google) <drive-shares-noreply@google.com>
-- | --
responder a: | "Maria Claudia Rubiano ..." <mcrubianot@udistrital.edu.co>
para: | mcrubianot@udistrital.edu.co
Cc: | esuasteguim@udistrital.edu.co,jvela.idexud@hotmail.com,dramirezv@udistrital.edu.co,jamahechar@correo.udistrital.edu.co
fecha: | 17 sept. 2019 11:11
asunto: | Acta No.17 - Kronos - Invitación para editar

Buenos días, comedidamente me permito remitir para su conocimiento y observaciones el acta de la reunión sostenida el día de hoy relacionada con los requerimientos iniciales del Subsistema de Contabilidad para Kronos.

Quedo atenta a sus comentarios

**Comment by mcrubianot** [comment]
Se recibe el siguiente correo

De: <esuasteguim@udistrital.edu.co>
Date: mié., 18 sept. 2019 a las 12:02
Subject: RE: Historias de Usuario - Plan de cuentas - Kronos
To: Oficina Asesora de Sistemas Universidad Distrital <computo@udistrital.edu.co>, Contab <contab@udistrital.edu.co>
Cc: Alvaro Mahecha <amahecha@udistrital.edu.co>


Buenas tardes Maria Claudia,

 

Revisando las historias de usuario enviadas tengo los siguientes comentarios,

 

no entiendo la diferencia entres la Variable HU-90 y HU-91
no tengo acceso de modificar al archivo en drive
no se donde se identifica que la cuenta contable se compone de 10 dígitos y se maneja a diferentes niveles, pero que los movimientos se registran todos a nivel 10
en el plan de cuenta no de detalla el centro de costo, solo se indica si la cuenta tiene o no asociados centros de costos, lo importante es determinar si la cuenta tuvo movimiento se debe incorporar un centro de costos para que el sistema se lo coloque a todos los movimientos.
Debe incluirse un check list que indique si la cuenta esta disponible o no para usarse
Debe incluirse un check list que identifique si la cuenta de ajuste al NMNC o no
En la opción de terceros se debe tener en cuenta los parámetros para cada caso
SI (se debe tener en cuenta si es una edición y la cuenta tiene movimientos, se debe solicitar un tercero para incorporarle el tercero a todos los movimientos, para evitar errores en los reportes)
No(se debe tener en cuenta si es una edición y la cuenta tiene movimientos, se debe borrar los terceros de los movimientos, para evitar errores en los reportes)
En el caso de retenciones debe solicitar que se indique que tipo de retención es y que porcentaje aplica, incluyendo un caso que no se indique porcentaje fijo)
Tener en cuenta que en el caso de Reteiva se debe diferenciar pues en estos casos en necesario indicar el valor el IVA.
Falta incluir el tipo de cuenta (Activo, pasivo, patrimonio, ingreso, gasto, orden, orden PC)
En el caso que sea una cuenta de banco debe indicarse el nit del banco asociado a la cuenta, el tipo de cuenta, el numero de la cuenta(banco), el consecutivo de la chequera.
No Entendí el ejemplo y el instructivo

Quedo atento a sus comentarios,
Cordial Saludo,

Ernesto Suastegui Molina
CPS
Sección de Contabilidad

**Comment by mcrubianot** [comment]
Se analizarán las observaciones y se ajustarán las HU

**Comment by Soulfilip-UD** [comment]
Se tuvo en cuenta las observaciones en las historias de usuario, y se ajusta de acuerdo al criterio del analista estas
Tarea finalizada

Proceeding to close Issue :space_invader:
