### ISSUE TITLE
Versión 2  - Historias de Usuario de Plan de Cuentas Contable

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#588]

**Comment by mcrubianot** [comment]
Se levantan las siguientes historias de usuario

https://docs.google.com/spreadsheets/d/1mehsBfQGdMY5WoiOMG9aCXm4w4TVK6nI/edit#gid=910264386

**Comment by mcrubianot** [comment]
Se envia el siguiente correo


de: | Oficina Asesora de Sistemas Universidad Distrital <computo@udistrital.edu.co>
-- | --
para: | Contab <contab@udistrital.edu.co>
Cc: | Ernesto Suastegui Molina <esuasteguim@udistrital.edu.co>,Alvaro Mahecha <amahecha@udistrital.edu.co>
Cco: | mcrubianot@udistrital.edu.co
fecha: | 17 sept. 2019 15:46
asunto: | Historias de Usuario - Plan de cuentas - Kronos

Buenas tardes. 

De conformidad con lo establecido en la sesión de trabajo del día de hoy, comedidamente nos permitimos remitir las historias de usuario relacionadas con la creación y consulta del plan de cuentas contables a ser implementado en el Sistema de Gestión Financiera Kronos.

Quedamos atentos a sus comentarios y observaciones al respecto.


Cordialmente, 
 
OFICINA ASESORA DE SISTEMAS

Link de las historias
https://docs.google.com/spreadsheets/d/1mehsBfQGdMY5WoiOMG9aCXm4w4TVK6nI/edit#gid=910264386

**Comment by mcrubianot** [comment]
Se reciben las siguientes observaciones

De: <esuasteguim@udistrital.edu.co>
Date: mié., 18 sept. 2019 a las 12:02
Subject: RE: Historias de Usuario - Plan de cuentas - Kronos
To: Oficina Asesora de Sistemas Universidad Distrital <computo@udistrital.edu.co>, Contab <contab@udistrital.edu.co>
Cc: Alvaro Mahecha <amahecha@udistrital.edu.co>


Buenas tardes Maria Claudia,

 

Revisando las historias de usuario enviadas tengo los siguientes comentarios,

no entiendo la diferencia entres la Variable HU-90 y HU-91
no tengo acceso de modificar al archivo en drive
no se donde se identifica que la cuenta contable se compone de 10 dígitos y se maneja a diferentes niveles, pero que los movimientos se registran todos a nivel 10
en el plan de cuenta no de detalla el centro de costo, solo se indica si la cuenta tiene o no asociados centros de costos, lo importante es determinar si la cuenta tuvo movimiento se debe incorporar un centro de costos para que el sistema se lo coloque a todos los movimientos.
Debe incluirse un check list que indique si la cuenta esta disponible o no para usarse
Debe incluirse un check list que identifique si la cuenta de ajuste al NMNC o no
En la opción de terceros se debe tener en cuenta los parámetros para cada caso
SI (se debe tener en cuenta si es una edición y la cuenta tiene movimientos, se debe solicitar un tercero para incorporarle el tercero a todos los movimientos, para evitar errores en los reportes)
No(se debe tener en cuenta si es una edición y la cuenta tiene movimientos, se debe borrar los terceros de los movimientos, para evitar errores en los reportes)
En el caso de retenciones debe solicitar que se indique que tipo de retención es y que porcentaje aplica, incluyendo un caso que no se indique porcentaje fijo)
Tener en cuenta que en el caso de Reteiva se debe diferenciar pues en estos casos en necesario indicar el valor el IVA.
Falta incluir el tipo de cuenta (Activo, pasivo, patrimonio, ingreso, gasto, orden, orden PC)
En el caso que sea una cuenta de banco debe indicarse el nit del banco asociado a la cuenta, el tipo de cuenta, el numero de la cuenta(banco), el consecutivo de la chequera.
No Entendí el ejemplo y el instructivo
 
Quedo atento a sus comentarios,

Cordial Saludo,
Ernesto Suastegui Molina
CPS
Sección de Contabilidad

**Comment by Soulfilip-UD** [comment]
Se crearon las historias de usuario y pendiente revisarlos por parte de Ernesto , usuario de contabilidad. Reunión el Martes 

Tarea Finalizada 
Proceeding to close Issue :space_invader:
