### ISSUE TITLE
Reunión Sección de Contabilidad - Presentación Argo, Agora y aprobación HU - Acta No.18

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#589]

**Comment by mcrubianot** [comment]
Se programa y se cita para dicha reunión el día 24 de septiembre a las 8:00 a..m, de acuerdo a lo establecido en la reunión del día 17 de septiembre.

**Comment by mcrubianot** [comment]
Se elabora para esta reunión el acta No.18 - Kronos

https://docs.google.com/document/d/1IWeuw-ekfc-PFt6dY_0fquI-jCbQvoC4-yFi_10tzLk/edit

**Comment by mcrubianot** [comment]
Se hace la respectiva reunión y se deja constancia en el acta que se relacionó en la nota anterior.

**Comment by mcrubianot** [comment]
Se programa sesión para el 1 de octubre en la Sección de Contabilidad para validar la HU que quedó pendiente de revisar.

**Comment by Soulfilip-UD** [comment]
Se compartio el acta y queda guardada en la carpeta de actas.
Todas las observaciones quedan en el acta

Tarea finalizada
Proceeding to close Issue :space_invader:

**Comment by mcrubianot** [comment]
Se recibe el siguiente correo. 

de: | esuasteguim@udistrital.edu.co
-- | --
para: | Maria Claudia Rubiano Torres <mcrubianot@udistrital.edu.co>
fecha: | 30 sept. 2019 17:02
asunto: | RE: Aprobacion actas 17 y 18
enviado por: | udistrital.edu.co

Hola Maria C buenas tardes,
El Acta 18 yo le hice unos cambio y le coloque mi nombre con la revisión, pero por favor me puedes renviar el acta 17 que no la encuentro en el correo,

Gracias,
Ernesto Suastegui

**Comment by mcrubianot** [comment]
Se recibe el siguiente correo


de: | Financiera - IDEXUD <financieraidexud@udistrital.edu.co>
-- | --
para: | "Maria Claudia Rubiano ..." <mcrubianot@udistrital.edu.co>
Cc: | Ernesto Suastegui Medina <esuasteguim@udistrital.edu.co>,Compras IDEXUD <comprasidexud@udistrital.edu.co>
fecha: | 7 oct. 2019 18:01
asunto: | Re: Acta No.18 - Kronos - Invitación para editar

Buenas tardes.

Revisado por Idexud.

Cordialmente,



Jhovan Alexander Vela Ruiz
Financiera - IDEXUD
