### ISSUE TITLE
Validación Gestión de Rubros y Apropiación Inicial - Subsistema de Presupuesto desplegado en test

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#591]

**Comment by mcrubianot** [comment]
Rubros Presupuestales
- Cuando se selecciona un rubro para crear un hijo, no se diferencia en donde estoy ubicadas, colocar algo que resalte
- Entiendo que si quiero editar el rubro ya creado, siempre y cuando no tenga movimientos, debe permitirme cambiar hasta el código y no lo está permitiendo, no habilita el recuadro del código
- Al continuar en la creación de un rubro hijo hasta un siguiente nivel, aparentemente lo crea por que se genera la alerta, pero cuando se va a consultar no aparece
- Una vez se creen todos los hijos de un rubro hasta último nivel y me ubico en él, debe dejarme ver el rubro completo
- Recuerden que el recuadro Entidad debe decir Centro Gestor y en el recuadro de Unidad ejecutora debe decir Área Funcional (esto se lo aclaré al ing. Felipe para socialización con los desarrolladores)
- Valores a la derecha y por favor colocar el punto de miles de pesos 
- Tener en cuenta las tildes
- No se observa para que vigencia se está creando el rubro
- Por favor tener en cuenta la longitud de caracteres para cada nivel del rubro
- No se observa en ninguna parte que nivel del rubro estoy creando,

Apropiaciones

- Al desplegar el árbol en la preasignación, se ve partido el rubro, es decir no es clara la visualización para que el rubro se vea completo
- Acá si me aparecen los rubros que cree en Rubros Presupuestales hasta el cuarto nivel
- En la comprobación por favor cambiar EGRESOS por GASTOS
-  Por favor tener en cuenta las tildes
- El titulo de comprobación, ingresos y egresos por favor disminuir la fuente por que está muy grande
- En la comprobación por favor colocar miles de pesos 
-  Al realizar la aprobación de la apropiación inicial esta generando un error
- Se sugiere resaltar el rubro donde estoy ubicada


Quedo atenta a sus comentarios y de aclarar algo estaré presta a lo que necesiten

**Comment by davidmm07** [comment]
Rubros Presupuestales

- [x] Cuando se selecciona un rubro para crear un hijo, colocar algo que resalte.**realizado**

- [x] Entiendo que si quiero editar el rubro ya creado, siempre y cuando no tenga movimientos, debe permitirme cambiar hasta el código y no lo está permitiendo, no habilita el recuadro del código.**Dentro del manual habria que aclarar que para el corregir el codigo es mejor eliminar el rubro incorrecto y volver a crearlo**
- [x] Al continuar en la creación de un rubro hijo hasta un siguiente nivel, aparentemente lo crea por que se genera la alerta, pero cuando se va a consultar no aparece. **Se encuentra el escenario mencionado y se corrige**
- [x] Una vez se creen todos los hijos de un rubro hasta último nivel y me ubico en él, debe dejarme ver el rubro completo. **El escenario no se evidencia que este fallando**
- [x] Recuerden que el recuadro Entidad debe decir Centro Gestor y en el recuadro de Unidad ejecutora debe decir Área Funcional (esto se lo aclaré al ing. Felipe para socialización con los desarrolladores) **Ya esta definido, sin embargo se sugiere definir cuales pueden ser los posibles Centros Gestores y Areas Funcionales para tenerlos en cuenta en los diferentes servicios**
- [x] Valores a la derecha y por favor colocar el punto de miles de pesos. **Falta subir algunos cambios a preprod**
- [x] No se observa para que vigencia se está creando el rubro. **Es transparente para cualquier vigencia, lo que importa es cuando se construyen los valores de apropiación(preasignación)** 
- [x] Por favor tener en cuenta la longitud de caracteres para cada nivel del rubro **En revisión** 
- [x] No se observa en ninguna parte que nivel del rubro estoy creando **En revisión** 

Apropiaciones

- [ ] Al desplegar el árbol en la preasignación, se ve partido el rubro, es decir no es clara la visualización para que el rubro se vea completo  **definir mejor esta observación, la información se ve clara** 
- [x] Acá si me aparecen los rubros que cree en Rubros Presupuestales hasta el cuarto nivel
En la comprobación por favor cambiar EGRESOS por GASTOS **realizado** 
- [ ] Por favor tener en cuenta las tildes **se esta revisando con Viviana** 
- [ ] El titulo de comprobación, ingresos y egresos por favor disminuir la fuente por que está muy grande  **pendiente** 
- [ ] En la comprobación por favor colocar miles de pesos **pendiente** 
- [ ] Al realizar la aprobación de la apropiación inicial esta generando un error **pendiente** 
- [x] Se sugiere resaltar el rubro

**Comment by mcrubianot** [comment]
Se hace la observación general que el tamaño de las fuentes de toda la vista en si está, muy grande.

La justificación de los rubros tanto padres como hijos se a a la izquierda

**Comment by Soulfilip-UD** [comment]
Ajustes realizados

<img width="725" alt="Screen Shot 2019-12-26 at 4 03 49 PM" src="https://user-images.githubusercontent.com/50924615/71490562-52efab00-27f9-11ea-80a6-94ea2f8b05a0.png">

Se puede proceder a cerrar el Issue 👾
