### ISSUE TITLE
Socializar los tipos de compromisos

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#592]
Socializar los tipos de compromisos con el Analista

**Comment by mcrubianot** [comment]
Se elabora el siguiente documento para socialización con los ingenieros y el líder técnico
https://docs.google.com/document/d/1BjeEAdJZm9TBff4HomEfOu66kcJExPcGEY41L5U_3bE/edit

**Comment by mcguegi** [comment]
De acuerdo a la socialización con la analista @mcrubianot se concreta que el modelo solamente debería tener Categoría y Tipo de Compromiso.

**Categoría del Compromiso**
```json
{
    "_id": "242bdaoiro3r49r4",
    "nombre": "CONTRATO",
    "activo": true,
    "fechaCreacion": "2018-09-01T05:00:00Z",
    "fechaModificacion":"2018-09-01T05:00:00Z"
}
```

**Tipo de Compromiso**
```json
{
    "_id": "68jsnvksjdkw0232",
    "idCategoria": "242bdaoiro3r49r4" ,
    "nombre": "CONTRATO DE OBRA",
    "descripcion": "Acuerdo temporal mediante el cual se contratar a un trabajador para que lleve a cabo un servicio concreto dentro de la empresa o una obra determinada.",
    "activo": true,
    "fechaCreacion": "2018-09-01T05:00:00Z",
    "fechaModificacion":"2018-09-01T05:00:00Z"
}
```
Queda pendiente reunión con Arquitectos y DBAs para proseguir con la implementación del modelo en el API Plan Cuentas Mongo :bee:

**Comment by Soulfilip-UD** [comment]
Compromisos socializados y no quedan ajustes

Proceeding to close Issue 👾
