### ISSUE TITLE
Análisis control de fuentes según información suministrada por la OAP

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#594]

**Comment by mcrubianot** [comment]
Se da inicio al análisis de la información suministrada por la Oficina Asesora de Planeación, de acuerdo con los archivos que se relacionan a continuación:
https://drive.google.com/open?id=1WDiayaQBzOPCnnMU4KtTP1VNqr639ddz
https://drive.google.com/open?id=1o_b7jouPJV6Nq-zmnutV3LEdj1rhH2Hw

**Comment by mcrubianot** [comment]
Se hace el análisis entendiendo el modelo que se presenta en los archivos antes relacionados y se construye el documento 

https://docs.google.com/spreadsheets/d/1jwh1b_N43ZKP1mmuFi4blkImM4eKZk7R8dohNvTnSR8/edit#gid=0

**Comment by DianaPatriciaRamirez** [comment]
Queda pendiente iniciar el proceso de generación de las historias de usuario y su correspondiente aprobación por parte del usuario de la Oficina Asesora de Planeación, sin embargo, para ello se generará otro issue. Se da por terminada esta actividad.
