### ISSUE TITLE
Validar necesidades por parte del analista

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#595]

**Comment by mcrubianot** [comment]
Se hace la validación del caso, se anexa documento correspondiente

https://docs.google.com/document/d/1iqI8QhQLKHI9vnROVgU18cKKqcMPq9-8h9Ow0c5ypJM/edit

**Comment by mcrubianot** [comment]
Se hace necesario realizar una socialización, con el fin de revisar en conjunto las observaciones acá planteadas

**Comment by Soulfilip-UD** [comment]
Puedes citar al equipo para la socialización en el espacio que tengas disponible, te recomiendo usar nuestro chat de Hangouts

**Comment by Soulfilip-UD** [comment]
Total de horas : 3 
Tarea finalizada
Proceeding to close Issue :space_invader:
