### ISSUE TITLE
Aprobación historia de Usuario Plan de Cuentas contable. Acta No.20 de 2019

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#598]

**Comment by mcrubianot** [comment]
Se hace la sesión de trabajo correspondiente se deja constancia en el acta No.20 de 2019

Se anexan los links de los documentos trabajados
https://docs.google.com/document/d/1CA7HCOjHWLcvbdsefY9-KUJrPJ0i7oM67ZvF2q17dy8/edit

https://drive.google.com/open?id=1D7t60JBH0I6Pf0J2SW-BTT25CnC1_VFe
https://drive.google.com/open?id=1xNWbfDfnOn_FF6PIsWMKF__oqzIK3Qf3
https://drive.google.com/open?id=1CRtj-QCFruhcgJBtRgfwdMTgze22ZLNQ

**Comment by DianaPatriciaRamirez** [comment]
HU 90-91-92 Plan de cuentas V3 Aprobada: https://drive.google.com/open?id=1jgNMD3_oy82FsBqQFN9e2STG_PTAYzAg
