### ISSUE TITLE
Revisión y aprobación procedimientos e historia s de usuario de Fuentes de Financiamiento y Productos. Acta No.22

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#602]

**Comment by mcrubianot** [comment]
Se levanta el acta correspondiente No.22 

https://docs.google.com/document/d/196KGzsAqFXkpNzPmb-MmgDdbT-c5Zyt6Na-dsUIJmbo/edit

**Comment by DianaPatriciaRamirez** [comment]
En acta 22 del 30 de octubre de 2019, el usuario de la Oficina Asesora de Planeación aprueba los procedimientos:

1. Creación_Productos_V2: https://www.draw.io/#G1Bt8FOQQBDCxR-JO_ZtLDEAi17hV9Ykd_
2. Creación_Fuente_Financiamiento_V2: https://www.draw.io/#G1b5_8LGn7_Qs_AYD5a_7GsNHeSRL_WUIa
3. Asignar productos a un rubro: https://www.draw.io/#G1FtLr5RSzTP37ghpxtzbjV7U8XScHqGDW

y las respectivas historias de usuario: 

1. Crear Productos
https://docs.google.com/spreadsheets/d/1dT4e0Ar-jDmqI73gOMALkVvyIueQ9LGF7X1hDlKj6Dk/edit#gid=852078008
2. Asignar Productos a un rubro
https://drive.google.com/open?id=1rQXDV6SE4MMn0rylUfC5tZN74_UQ3UavWBlsSZUtMBs
