### ISSUE TITLE
Creación de rubros del Idexud y pruebas de la funcionalidad - Rubros presupuestales

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#609]

**Comment by mcrubianot** [comment]
Con el fin de validar la creación de rubros presupuestales, se procede a la creación de los rubros del Idexud, de tal manera que sirvan de pruebas dentro de los diferentes procedimientos a desarrollar.

Se encontraron aspectos tales como:

- [ ] Me saco del sistema y al volver a ingresas y no despliego la lista de rubros

- [ ] Hay momentos en los que se genera un error "Error interno en el servidor- Cargar-GLOBAL.menu

- [ ] Se crearon dos rubros del grupo 2 y 3 y al editarlos y tratar de cambiar que corresponde al área funcional Idexud no deja. No sé si esto se subsanaría con el ingreso de un rol que corresponda al Idexud.

- [ ] Se hacen pruebas de borrar un nivel y lo permite sin problema

- [ ] Se hace la prueba de editar y no se presentaron inconvenientes

- [ ] Se crea un rubro a este nivel 3-00-991-00-00-29-0720-1 y aparentemente queda creado (esto no sucedió en el primer ejercicio que se hizo en horas de la mañana) pero al desplegar no figura. Y si se da click en guardar, emite el siguiente error "Error. No se Pudo registrar el rubro, compruebe que no exista un rubro con el mismo código o que este código sea admitido.". Se hace el ejercicio de crear uno nuevo 3-00-991-00-00-29-0720-2 y sucede lo mismo aparentemente lo crea pero al desplegar el árbol no se ve.

- [ ] Se crea el rubro 3-00-991-00-00-29-6198 y me lo guarda sin inconveniente, pero al desplegar el árbol para corrobrar me lo muestra dos veces y si lo quito se me desaparecen los dos.

**Comment by mcrubianot** [comment]
Se envio correo con los pantallazos correspondientes, después de las indicaciones por parte del Ing Juan Camilo.

**Comment by juancsr** [comment]
Se hicieron ajustes correspondientes para registros de nivel 8 en adelante.

Issue resolved at: https://github.com/udistrital/plan_cuentas_mongo_crud/issues/158

**Comment by mcrubianot** [comment]
El día de hoy se hacen pruebas con el ingeniero Juan Camilo y se observa que la creación de los rubros del nivel 8 en adelante fue ajustado.

Considero pertinente que el tema está finiquitado y solo quedaría la validación del por parte del usuario.
