### ISSUE TITLE
Socialización Inicio de mes y vigencia y Cierre de mes y vigencia

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#611]

**Comment by mcrubianot** [comment]
Se elaboran los siguientes documentos
Inicio
https://drive.google.com/open?id=1vEY2sLsM75kdFp4W2c2K8JjVnyISPtpWETqn-pQrJds
Cierre
https://drive.google.com/open?id=1JWKcGfaKcIbkdZzUD81pIuy7i1_bviNSnzmwuugPMyY

**Comment by mcrubianot** [comment]
Se realiza sesión de trabajo el día 9 de diciembre de 2019 a las 8: 00.

Se hacen las aclaraciones del caso a los ingenieros Neider, Carlos y Felipe.

Se comparte el documento ejecución de gastos para el análisis de como deben quedar los datos para el cierre.

**Comment by DianaPatriciaRamirez** [comment]
Se finaliza actividad. Se recomienda que si alguno de los ingenieros que están desarrollando estos módulo de inicio (@NeiderFajardo Neider Fajardo) y cierre de vigencia (@CarlosGutierrezArdila Carlos Gutiérrez) tienen alguna duda por favor consultar con Maria Claudia Rubiano.
