### ISSUE TITLE
Corrección Historias de usuario

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#613]

**Comment by mcrubianot** [comment]
Se corrigen las siguientes HU por solicitud del líder técnico

HU - 46 Modificaciones Presupuestales V3 https://docs.google.com/spreadsheets/d/17N6NHjPBpVMrEp55Csjl4aFKhph37BUZcnjORt1s1mw/edit#gid=2083944881

HU - 12 A 13 Crear Fuentes de Financiamiento V3 https://docs.google.com/spreadsheets/d/17yTvgXMPHdUq0ZZQvo7Iq_I_gJlhpQXf8_lf5L05B2U/edit#gid=618226458

**Comment by DianaPatriciaRamirez** [comment]
La analista de requerimientos revisó las observaciones del líder técnico Felipe Canasto y se confirman los siguientes datos:

- [x] [HU - 46 Modificaciones Presupuestales V3](https://docs.google.com/spreadsheets/d/17N6NHjPBpVMrEp55Csjl4aFKhph37BUZcnjORt1s1mw/edit#gid=2083944881). Se confirma que el formato de la fecha es el mismo que se indicó en la HU: dd/mm/aaaa

- [x] [HU - 12 A 13 Crear Fuentes de Financiamiento V3](https://docs.google.com/spreadsheets/d/17yTvgXMPHdUq0ZZQvo7Iq_I_gJlhpQXf8_lf5L05B2U/edit#gid=618226458). En la consulta de fuentes se debe visualizar el tipo de modificación en la fuente.

Se cierra issue.
