### ISSUE TITLE
Socialización modelo de comprobantes contables

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente#614]

**Comment by mcrubianot** [comment]
Con la finalidad de aclarar un poco más el tema de los comprobantes de contabilidad se elabora el siguiente documento:

https://docs.google.com/document/d/1eEzz5Q5FMKTu6ic-mlJK-0g8JHzlWhUT/edit#heading=h.gjdgxs

Y se anexa el listado resumen de comprobantes (ejemplo).

https://drive.google.com/open?id=1a9G1yOx55szU-cQi8jiZERjE37kZdWOg

**Comment by DianaPatriciaRamirez** [comment]
Ingenieros David @davidmm07 y Felipe @Soulfilip-UD por favor revisen esta documentación y si existe alguna duda, consultarla con Maria Claudia antes del 27 de diciembre.
